#!/usr/bin/env bash
# Brings up the API dev server once MongoDB is ready.
#
# Steps (all idempotent so they are safe to run on every agent start):
#   1. Wait for the local mongod (started by start-mongo.sh) to accept pings.
#   2. Initiate the `rs0` replica set if it has not been initiated yet.
#   3. Wait until the node reports PRIMARY (required before transactions work).
#   4. Ensure a local dev `.env` exists (the dev script uses `node --env-file`,
#      which errors if the file is missing). A pre-existing `.env` is respected.
#   5. Start the dev server (`pnpm dev`) in the foreground.
set -euo pipefail

cd "$(dirname "$0")/../.." # repo root

MONGO_URI_LOCAL="mongodb://127.0.0.1:27017/?replicaSet=rs0"

echo "[start-api] waiting for mongod to accept connections..."
until mongosh --quiet --host 127.0.0.1 --port 27017 --eval 'db.runCommand({ ping: 1 })' >/dev/null 2>&1; do
  sleep 1
done

echo "[start-api] ensuring rs0 replica set is initiated..."
mongosh --quiet --host 127.0.0.1 --port 27017 --eval '
  try {
    rs.status();
  } catch (e) {
    if (e.codeName === "NotYetInitialized" || e.code === 94) {
      rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "127.0.0.1:27017" }] });
    } else {
      throw e;
    }
  }
'

echo "[start-api] waiting for PRIMARY..."
until [ "$(mongosh --quiet --host 127.0.0.1 --port 27017 --eval 'try { rs.status().myState } catch (e) { 0 }' 2>/dev/null | tail -1)" = "1" ]; do
  sleep 1
done

if [ ! -f .env ]; then
  echo "[start-api] no .env found; writing local dev defaults..."
  cat > .env <<EOF
# Local development environment (gitignored). Auto-generated by .cursor/scripts/start-api.sh.
PORT=3000
TEST_MODE=true
MONGO_URI=${MONGO_URI_LOCAL}
VANTAGE_API_SECRET=local-dev-secret
SHEET_SYNC_MODE=disabled
EOF
fi

echo "[start-api] starting API dev server on http://localhost:3000 ..."
exec pnpm dev
