#!/usr/bin/env bash
# Brings up the API dev server once MongoDB is ready.
#
# Steps (all idempotent so they are safe to run on every agent start):
#   1. Wait for the local mongod (started by start-mongo.sh / ensure-cloud-runtime.sh).
#   2. Initiate the `rs0` replica set if it has not been initiated yet.
#   3. Wait until the node reports PRIMARY (required before transactions work).
#   4. Ensure a local dev `.env` exists (the dev script uses `node --env-file`,
#      which errors if the file is missing). A pre-existing `.env` is respected.
#   5. Export local-only overrides, then start `pnpm dev` in the foreground.
#
# Cloud dashboard secrets currently inject Atlas MONGO_URI with TEST_MODE=false
# and SHEET_SYNC_MODE=queued. `node --env-file=.env` does **not** override
# already-set process env, so the exports below are required to keep Cloud
# agents on local Mongo (`testvantagemovers`) and to skip Sheets / RingCentral
# writes. Do not point this script at vantagemovers or historicalvantagemovers.
set -euo pipefail

cd "$(dirname "$0")/../.." # repo root

MONGO_URI_LOCAL="mongodb://127.0.0.1:27017/?replicaSet=rs0"

echo "[start-api] waiting for mongod to accept connections..."
until mongosh --quiet --host 127.0.0.1 --port 27017 --eval 'db.runCommand({ ping: 1 })' >/dev/null 2>&1; do
  sleep 1
done

echo "[start-api] ensuring rs0 replica set is initiated..."
mongosh --quiet --host 127.0.0.1 --port 27017 --eval '
  try {
    rs.status();
  } catch (e) {
    if (e.codeName === "NotYetInitialized" || e.code === 94) {
      rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "127.0.0.1:27017" }] });
    } else {
      throw e;
    }
  }
'

echo "[start-api] waiting for PRIMARY..."
until [ "$(mongosh --quiet --host 127.0.0.1 --port 27017 --eval 'try { rs.status().myState } catch (e) { 0 }' 2>/dev/null | tail -1)" = "1" ]; do
  sleep 1
done

if [ ! -f .env ]; then
  echo "[start-api] no .env found; writing local-only Cloud defaults..."
  cat > .env <<EOF
# Local development environment (gitignored). Auto-generated by .cursor/scripts/start-api.sh.
PORT=3000
TEST_MODE=true
MONGO_URI=${MONGO_URI_LOCAL}
VANTAGE_API_SECRET=local-dev-secret
SHEET_SYNC_MODE=disabled
WRITE_SOURCE_LEAD_SHEETS=false
RINGCENTRAL_CREATE_CALL_LEADS=false
RINGCENTRAL_SHADOW_CALL_LEADS=false
RINGCENTRAL_WEBHOOK_ENABLED=false
RINGCENTRAL_CALL_LOG_SYNC_ENABLED=false
RINGCENTRAL_ANALYTICS_RECONCILE_ENABLED=false
RINGCENTRAL_COLLECTION_MODE=test
SHEET_SYNC_QUEUE_LOCAL_PUBLISH=false
EOF
fi

# Force local-only runtime. Dashboard-injected secrets win over --env-file
# unless we export replacements in this process.
export PORT="${PORT:-3000}"
export TEST_MODE=true
export MONGO_URI="$MONGO_URI_LOCAL"
export SHEET_SYNC_MODE=disabled
export WRITE_SOURCE_LEAD_SHEETS=false
export RINGCENTRAL_CREATE_CALL_LEADS=false
export RINGCENTRAL_SHADOW_CALL_LEADS=false
export RINGCENTRAL_WEBHOOK_ENABLED=false
export RINGCENTRAL_CALL_LOG_SYNC_ENABLED=false
export RINGCENTRAL_ANALYTICS_RECONCILE_ENABLED=false
export RINGCENTRAL_COLLECTION_MODE=test
export SHEET_SYNC_QUEUE_LOCAL_PUBLISH=false
export RC_TOKEN_STORE=file
: "${VANTAGE_API_SECRET:=local-dev-secret}"
export VANTAGE_API_SECRET

echo "[start-api] starting API on http://localhost:3000 (local Mongo, TEST_MODE=true, sheets/RC writes off)..."
exec pnpm dev
