/**
 * Stable Operations Registry error codes (contract §6).
 *
 * These identifiers are safe to expose in HTTP responses and client surfaces.
 * Pair them with human-readable `message` text and optional `remediation` data.
 */
export const REGISTRY_ERROR_CODES = {
  FORBIDDEN: "REGISTRY_FORBIDDEN",
  NOT_FOUND: "REGISTRY_NOT_FOUND",
  IMMUTABLE_FIELD: "REGISTRY_IMMUTABLE_FIELD",
  DUPLICATE_IDENTIFIER: "REGISTRY_DUPLICATE_IDENTIFIER",
  AMBIGUOUS_RESOLUTION: "REGISTRY_AMBIGUOUS_RESOLUTION",
  DEPENDENCY_CONFLICT: "REGISTRY_DEPENDENCY_CONFLICT",
  STALE_REVISION: "REGISTRY_STALE_REVISION",
  CPL_SCHEDULE_GAP: "CPL_SCHEDULE_GAP",
  CPL_SCHEDULE_OVERLAP: "CPL_SCHEDULE_OVERLAP",
  CPL_MISSING_RATE: "CPL_MISSING_RATE",
  CPL_PREVIEW_STALE: "CPL_PREVIEW_STALE",
  RINGCENTRAL_ROUTE_UNVALIDATED: "RINGCENTRAL_ROUTE_UNVALIDATED",
  RINGCENTRAL_ROUTE_INVALID: "RINGCENTRAL_ROUTE_INVALID",
  RINGCENTRAL_VALIDATION_UNAVAILABLE: "RINGCENTRAL_VALIDATION_UNAVAILABLE",
  ACTOR_SIGNATURE_INVALID: "REGISTRY_ACTOR_SIGNATURE_INVALID",
  ACTOR_SIGNATURE_EXPIRED: "REGISTRY_ACTOR_SIGNATURE_EXPIRED",
  ACTOR_SIGNATURE_MISSING: "REGISTRY_ACTOR_SIGNATURE_MISSING",
} as const;

export type RegistryErrorCode =
  (typeof REGISTRY_ERROR_CODES)[keyof typeof REGISTRY_ERROR_CODES];

export type RegistryRemediation = {
  summary: string;
  action?: string;
  fields?: string[];
  entity_type?: string;
  entity_id?: string;
  [key: string]: unknown;
};
