/**
 * Reads the **Leads** tab from ORIGINAL_GOOGLE_SHEET_ID and writes a markdown dump
 * of the nine owner-facing columns (see LEAD_SHEET_HEADERS in api/utils/sheetRows.ts).
 *
 * Run: pnpm run sheets:dump-leads-columns
 *
 * Output: scripts/leads-sheet-columns-preview.md (overwritten each run)
 *
 * Rows are streamed to disk so large tabs (1000s of rows) do not balloon memory.
 *
 * Optional env:
 * - LEADS_DUMP_MAX_ROWS — max data rows after the header (default: all rows)
 */

import { createWriteStream } from "node:fs";
import path from "node:path";
import process from "node:process";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { google } from "googleapis";
import dotenv from "dotenv";
import { LEAD_SHEET_HEADERS, LEAD_SHEET_NAME } from "../api/utils/sheetRows";

dotenv.config();

function requiredEnv(name: string): string {
  const raw = process.env[name];
  const v = typeof raw === "string" ? raw.trim() : "";
  if (!v) {
    console.error(`Missing ${name}. Set it in .env (see package.json sheets:dump-leads-columns).`);
    process.exit(1);
  }
  return v;
}

const serviceAccountFile = requiredEnv("SERVICE_ACCOUNT_LOCAL_FILE");
const originalSpreadsheetId = requiredEnv("ORIGINAL_GOOGLE_SHEET_ID");

/** First nine columns on the Leads tab (owner-facing fields before Booked / sources / etc.). */
const COLUMNS_TO_DUMP = LEAD_SHEET_HEADERS.slice(0, 9);

function escapeSheetTitleForRange(title: string): string {
  return `'${title.replace(/'/g, "''")}'`;
}

function normalizeHeader(h: string): string {
  return h.trim().replace(/\s+/g, " ").toLowerCase();
}

function parseMaxRows(): number | undefined {
  const raw = process.env.LEADS_DUMP_MAX_ROWS?.trim();
  if (!raw) return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n) || n < 0) {
    console.warn(
      `Ignoring invalid LEADS_DUMP_MAX_ROWS=${JSON.stringify(raw)}; dumping all rows.`,
    );
    return undefined;
  }
  return n === 0 ? undefined : n;
}

function cellDisplay(row: string[] | undefined, colIndex: number): string {
  if (!row) return "";
  const v = row[colIndex];
  if (v === undefined || v === null) return "";
  const s = String(v).trim();
  return s.length === 0 ? "*(empty)*" : s;
}

async function main(): Promise<void> {
  const maxRows = parseMaxRows();

  const keyFile = path.join(process.cwd(), serviceAccountFile);

  const auth = new google.auth.GoogleAuth({
    keyFile,
    scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
  });

  const sheetsApi = google.sheets({ version: "v4", auth });

  const { data: meta } = await sheetsApi.spreadsheets.get({
    spreadsheetId: originalSpreadsheetId,
    fields:
      "properties.title,sheets(properties(title,gridProperties(rowCount,columnCount)))",
  });

  const spreadTitle = meta.properties?.title ?? "(untitled)";
  const leadsMeta = meta.sheets?.find(
    (s) => s.properties?.title?.trim() === LEAD_SHEET_NAME,
  );

  if (!leadsMeta?.properties?.title) {
    console.error(
      `Sheet named "${LEAD_SHEET_NAME}" was not found in this spreadsheet.`,
    );
    process.exit(1);
  }

  /** Sheet grid size; API expands this as rows are added. Large fallback avoids truncating huge tabs if metadata is missing. */
  const rowCount = leadsMeta.properties.gridProperties?.rowCount ?? 50_000;
  /** Leads currently uses ≤16 logical columns; Z covers header lookup even if order shifts. */
  const endCol = "Z";

  const range = `${escapeSheetTitleForRange(LEAD_SHEET_NAME)}!A1:${endCol}${rowCount}`;

  const { data } = await sheetsApi.spreadsheets.values.get({
    spreadsheetId: originalSpreadsheetId,
    range,
    majorDimension: "ROWS",
    valueRenderOption: "FORMATTED_VALUE",
  });

  const rows = data.values ?? [];
  if (rows.length === 0) {
    console.error("Leads sheet returned no rows.");
    process.exit(1);
  }

  const headerRow = rows[0].map((c) => (c == null ? "" : String(c)));
  const headerNormToIndex = new Map<string, number>();
  for (let i = 0; i < headerRow.length; i++) {
    headerNormToIndex.set(normalizeHeader(headerRow[i]), i);
  }

  const columnIndices: { name: string; index: number | undefined }[] =
    COLUMNS_TO_DUMP.map((name) => ({
      name,
      index: headerNormToIndex.get(normalizeHeader(name)),
    }));

  const missing = columnIndices.filter((c) => c.index === undefined);

  const preamble: string[] = [
    "<!-- Generated by scripts/dump-leads-sheet-columns.ts — do not edit by hand -->",
    "",
    `# Leads sheet column preview`,
    "",
    `- **Spreadsheet**: ${spreadTitle}`,
    `- **Spreadsheet ID**: \`${originalSpreadsheetId}\``,
    `- **Sheet**: \`${LEAD_SHEET_NAME}\``,
    `- **Range read**: \`${range}\``,
  ];
  if (maxRows !== undefined) {
    preamble.push(`- **Row limit**: ${maxRows} data row(s) after header`);
  }
  preamble.push(
    "",
    "## How to read another tab from the same spreadsheet",
    "",
    "1. Call `spreadsheets.get` with `spreadsheetId` = `ORIGINAL_GOOGLE_SHEET_ID` (or whichever workbook you need) to confirm the sheet title.",
    "2. Call `spreadsheets.values.get` with a range like `'Sheet Name'!A1:Z50000` — quote the title and double any `'` inside it (`O'Brien` → `'O''Brien'`).",
    "3. Treat row 1 as headers: normalize names (trim, collapse spaces) and map each logical column to its column index, then read values row by row.",
    "",
  );

  if (missing.length > 0) {
    preamble.push(
      "## Header mapping warnings",
      "",
      "These expected columns were **not** found on row 1 (check spelling/casing):",
    );
    for (const m of missing) {
      preamble.push(`- \`${m.name}\``);
    }
    preamble.push("", "Headers found on row 1:", "");
    for (const h of headerRow) {
      if (h.trim()) preamble.push(`- \`${h}\``);
    }
    preamble.push("");
  }

  const dataRows = rows.slice(1);
  const limited = maxRows !== undefined ? dataRows.slice(0, maxRows) : dataRows;

  const outPath = path.join(
    process.cwd(),
    "scripts",
    "leads-sheet-columns-preview.md",
  );

  async function* rowSections(): AsyncGenerator<string> {
    yield preamble.join("\n") + "\n";
    yield "## Rows\n\n";

    let printedNonBlank = 0;
    for (let i = 0; i < limited.length; i++) {
      const sheetRow = i + 2;
      const row = limited[i];
      const cells = Array.isArray(row)
        ? row.map((c) => (c == null ? "" : String(c)))
        : [];

      const isBlank = cells.every((c) => c.trim() === "");
      if (isBlank) continue;

      printedNonBlank++;
      const rowObj: Record<string, string> = {};
      for (const col of columnIndices) {
        const raw =
          col.index === undefined
            ? "(column missing from header row)"
            : cellDisplay(cells, col.index);
        rowObj[col.name] = raw === "*(empty)*" ? "" : raw;
      }
      yield `### Sheet: ${LEAD_SHEET_NAME} — row ${sheetRow}\n\n`;
      yield "```json\n";
      yield `${JSON.stringify(rowObj, null, 2)}\n`;
      yield "```\n\n";
    }

    yield "---\n\n";
    yield `*${printedNonBlank} non-blank row(s) written; scanned ${limited.length} data row(s) after header (${dataRows.length} row object(s) returned in range).*\n`;
  }

  await pipeline(Readable.from(rowSections()), createWriteStream(outPath));

  console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
