import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';

async function main(){
 const local=JSON.parse(await readFile(join(tmpdir(),'vantage-csi07-local/session.json'),'utf8'));
 assert.equal(local.env.MONGO_URI,'mongodb://127.0.0.1:27189/?replicaSet=csi01');assert.equal(local.env.TEST_MONGO_DATABASE_NAME,'testvantagemovers_csi07preview');assert.equal(local.env.TEST_MODE,'true');
 Object.assign(process.env,local.env);
 const mongoose=(await import('mongoose')).default;
 const {connectMongo}=await import('../src/db.js');const {csiDataset}=await import('../src/config/domain/salesIntelligence.js');
 const {getContactNumberModel}=await import('../src/models/ContactNumber.js');const {getOutreachRecordModel}=await import('../src/models/OutreachRecord.js');
 const {getIntelligenceRunModel}=await import('../src/models/IntelligenceRun.js');const {getIntelligenceFindingModel}=await import('../src/models/IntelligenceFinding.js');
 const {getIntelligenceEffectModel}=await import('../src/models/IntelligenceEffect.js');const {getOutreachFollowupModel}=await import('../src/models/OutreachFollowup.js');
 const {intelligenceEnvelopeSchema}=await import('../src/validation/intelligence/intelligenceEnvelope.validation.js');
 const {defaultCsiPolicy}=await import('../src/services/salesIntelligence/policy.js');
 const {getIntelligenceEvidenceSnapshotModel}=await import('../src/models/IntelligenceEvidenceSnapshot.js');
 const {loadReadScope,readIntelligenceEvidence}=await import('../src/services/salesIntelligence/analysis/reads.js');
 const {payloadHash}=await import('../src/services/salesIntelligence/transactions.js');
 const {renderIntelligencePrompt,intelligenceSchemaDigest}=await import('../src/services/salesIntelligence/analysis/run.js');
 const {CSI_PROMPT_VERSION}=await import('../src/services/salesIntelligence/analysis/contracts.js');
 await connectMongo();assert.equal((await mongoose.connection.db!.admin().command({hello:1})).setName,'csi01');
 const oid=()=>new mongoose.Types.ObjectId(),now=new Date();
 const number=await getContactNumberModel().create({e164:`+1202${String(Date.now()).slice(-7)}`,digits_reversed:randomUUID(),classification:'customer',contact_eligibility:{state:'allowed'},provider_names:['CSI-18 synthetic'],search_terms:['csi18 synthetic'],first_observed_at:now,last_activity_at:now});
 const record=await getOutreachRecordModel().create({subject:{kind:'number_review',contact_number_id:number._id},primary_contact_number_id:number._id,state:'open',trigger_kind:'owner_open',trigger_at:now,policy_version:defaultCsiPolicy().version});
 const fixtureRunId=oid(),fixtureEvidenceId=oid(),subject=`number:${number._id}`;
 const evidence=await readIntelligenceEvidence(await loadReadScope({_id:fixtureRunId,subject_key:subject,contact_number_id:number._id,outreach_record_id:record._id}),{tool:'get_intelligence_context',args:{}});
 const evidenceDigest=payloadHash(evidence);
 const output=intelligenceEnvelopeSchema.parse({schema_version:'csi-envelope-v1',summary:{overview:'Synthetic Owner intervention demonstration',customer_wanted:'Moving estimate',money_and_dates:'No date agreed',outcome:'Follow-up pending',commitments:'Prepare estimate',discrepancies:'None',finding_keys:['callback']},findings:[{key:'callback',kind:'next_step',claim:'Prepare the synthetic estimate',basis:'vantage_record',actor:'rep',speaker_ref:null,action_status:'requested',clarity:'clear',confidence:null,evidence:[{source:'vantage_record',snapshot_id:String(fixtureEvidenceId),record_type:'contact_number',record_id:String(number._id),field_paths:['classification']}],value:{action_kind:'send_estimate',description:'Prepare the synthetic estimate',date_text:null,timezone_text:null,target_followup_id:null}}],next_step_suggestion:{action_kind:'review',description:'Review synthetic estimate with the Owner',date_text:null,timezone_text:null,target_followup_id:null,rationale:'Owner review requested',finding_keys:['callback']},owner_instruction_assessments:[]});
 const run=await getIntelligenceRunModel().create({_id:fixtureRunId,rendered_prompt:renderIntelligencePrompt(subject),schema_digest:intelligenceSchemaDigest(),manifest_digest:payloadHash([{id:String(fixtureEvidenceId),digest:evidenceDigest}]),manifest_snapshot_ids:[fixtureEvidenceId],evidence_count:1,evidence_bytes:Buffer.byteLength(JSON.stringify(evidence)),...csiDataset(),subject_key:`number:${number._id}`,contact_number_id:number._id,outreach_record_id:record._id,job_id:oid(),input_fingerprint:'fixture',prompt_version:CSI_PROMPT_VERSION,schema_version:'csi-envelope-v1',model_version:'synthetic-no-provider',output,finalized_at:now,completed_at:now,status:'completed',mode:'initial'});
 await getIntelligenceEvidenceSnapshotModel().create({_id:fixtureEvidenceId,run_id:run._id,...csiDataset(),subject_key:subject,source_type:'tool_response',source_id:subject,source_revision:'1',tool_name:'get_intelligence_context',tool_call_id:payloadHash({tool:'get_intelligence_context',args:{}}),arguments:{},response:evidence,content_digest:evidenceDigest,retrieved_at:now,completeness:{complete:evidence.page.complete,cursor:evidence.page.next_cursor,missing_ranges:evidence.page.missing_ranges}});
 const finding=await getIntelligenceFindingModel().create({run_id:run._id,key:'callback',assertion:output.findings[0],kind:'next_step',contact_number_id:number._id,outreach_record_id:record._id,prompt_version:CSI_PROMPT_VERSION,schema_version:'csi-envelope-v1',model_version:'synthetic-no-provider',validation:{schema_ok:true,source_snapshots_valid:true}});
 const action=await getOutreachFollowupModel().create({outreach_record_id:record._id,commitment_key:`csi18:${run._id}`,kind:'send_estimate',description:'Prepare the synthetic estimate',origin:'rep_promise',due_at:null,base_attention_due_at:null,source_finding_ids:[finding._id]});
 await getIntelligenceEffectModel().create({run_id:run._id,finding_id:finding._id,finding_key:'callback',effect_kind:'create_followup',target_key:`followup:${action._id}`,target_id:action._id,status:'applied',previous:{},current:{},applied_at:now});
 await getContactNumberModel().updateOne({_id:number._id},{$set:{running_summary:{text:output.summary.overview,run_id:run._id,evidence_digest:'fixture',computed_at:now}}});
 const base='http://127.0.0.1:3108',prefix='/api/proxy/api/v1/admin/sales-intelligence';
 const login=async(role:string)=>{const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:`${role}@csi07.example.test`,password:local.password})});assert.equal(r.status,200);return r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');};
 const cookie=await login('owner');
 const read=async()=>{const r=await fetch(`${base}${prefix}/analysis-runs/${run._id}?scope=production`,{headers:{cookie}});assert.equal(r.status,200);return r.json();};
 const send=async(body:object,key:string)=>{const r=await fetch(`${base}${prefix}/analysis-runs/${run._id}/confirm?scope=production`,{method:'POST',headers:{cookie,'content-type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const before=await getIntelligenceEffectModel().countDocuments({run_id:run._id});const value=await read();await read();assert.equal(await getIntelligenceEffectModel().countDocuments({run_id:run._id}),before);
 const body={command:'confirm_run',expected_revision:value.data.revision,expected_output_digest:value.data.output_digest};const key=randomUUID();
 assert.equal((await send(body,key)).status,200);assert.equal((await send(body,key)).body.data.replayed,true);assert.equal((await send({...body,expected_output_digest:'changed'},key)).status,409);assert.equal((await send(body,randomUUID())).status,409);
 const admin=await login('admin');assert.equal((await fetch(`${base}${prefix}/analysis-runs/${run._id}?scope=production`,{headers:{cookie:admin}})).status,403);
 assert.equal((await fetch(`${base}${prefix}/analysis-runs/${run._id}/confirm?scope=production`,{method:'POST',headers:{cookie:admin,'content-type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify(body)})).status,403);
 const proof={number_id:String(number._id),run_id:String(run._id),finding_id:String(finding._id),action_id:String(action._id),url:`${base}/sales-intelligence?view=numbers&number=${number._id}&analysis_run=${run._id}`,checks:['real Owner BFF read','read has no effects','confirmation','durable duplicate','changed-payload conflict','stale revision conflict','Admin read/write denied'],at:new Date().toISOString()};
 await writeFile('docs/call-sales-intelligence/workspace/evidence/csi-18/http.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));await mongoose.disconnect();
}
main().catch(async e=>{console.error(e instanceof Error?e.message:'CSI18 local failure');process.exitCode=1;await (await import('mongoose')).default.disconnect();});
