/**
 * CF-AC (2026-09-24): verbatim copy of vantage-admin@539a628 lib/api/salesIntelligence.ts (the production Admin),
 * generated by `git -C ../vantage-admin show 539a628:lib/api/salesIntelligence.ts`. Used only by the contract tooling
 * to prove fixtures parse with the production Admin's Outreach read schema. Never edit to make a fixture pass; re-copy.
 */
/* eslint-disable */
// @ts-nocheck
import { z } from 'zod';
// Consumer schemas mirror current server dto.ts/numberActivity DTOs. No domain derivation.
const agent = z.object({ id: z.string(), name: z.string() });
export const availabilitySchema=z.object({action:z.string(),enabled:z.boolean(),blocker_codes:z.array(z.string()),target_id:z.string(),expected_revision:z.number()});
export const attachmentSchema=z.object({id:z.string(),revision:z.number(),contact_number_id:z.string(),lead_ref:z.object({model:z.enum(['FormLead','CallLead']),id:z.string()}),state:z.string(),certainty_label:z.string().nullable(),
 lead_snapshot:z.object({name:z.string().nullable(),job_no:z.string().nullable(),source_label:z.string().nullable(),booked:z.boolean(),cancelled:z.boolean(),duplicate:z.boolean(),bad_lead:z.boolean()}).nullable(),
 evidence:z.array(z.object({source:z.string(),field_path:z.string(),observed_at:z.string(),window_from:z.string().nullable(),window_to:z.string().nullable()})),
 decided_at:z.string().nullable(),decision_reason:z.string().nullable(),history:z.array(z.object({from:z.string().nullable(),to:z.string().nullable(),at:z.string().nullable(),by:z.string().nullable(),reason:z.string().nullable()})),
 allowed_actions:z.array(availabilitySchema).optional()});
export const attachmentsSchema=z.object({data:z.object({items:z.array(attachmentSchema),next_cursor:z.string().nullable()})});
export const reviewItemsSchema=z.object({data:z.object({items:z.array(z.object({id:z.string(),revision:z.number(),subject_key:z.string(),cause_kind:z.string(),state:z.string(),opened_at:z.string(),resolution_reason:z.string().nullable(),evidence_refs:z.array(z.string()),allowed_actions:z.array(availabilitySchema)})),cursor:z.string().nullable()})});
export const repSchema=z.object({id:z.string(),revision:z.number(),agent_id:z.string(),agent_name:z.string(),rc_account_id:z.string(),rc_extension_id:z.string(),rc_extension_name:z.string().nullable(),rc_extension_number:z.string().nullable(),role_kind:z.string(),status:z.string(),effective_from:z.string(),effective_to:z.string().nullable(),nudge_channels_allowed:z.array(z.string()),rc_direct_numbers:z.array(z.string()).default([]),rc_team_messaging_person_id:z.string().nullable().optional(),history:z.array(z.object({at:z.string().nullable(),by:z.string().nullable(),change:z.string().nullable()})),metrics:z.object({status:z.literal('unknown'),interactions_total:z.null()})});
/** Owner review records pager on every unique link; SMS-to-rep only when the stored snapshot has exactly one DID. Team Messaging person ids stay unresolved. */
export function reviewedNudgeChannels(directNumbers: readonly string[] | undefined): string[] {
  return (directNumbers?.length ?? 0) === 1 ? ["pager", "sms_to_rep"] : ["pager"];
}
export const directoryUserSchema=z.object({extension_id:z.string(),extension_name:z.string().nullable(),status:z.string(),candidates:z.array(z.object({agent_id:z.string(),agent_name:z.string(),basis:z.string()})),extension_number:z.string().nullable().optional(),direct_numbers:z.array(z.string()).optional(),directory_status:z.string().optional(),rc_account_id:z.string().optional(),attached_agent:z.object({id:z.string(),name:z.string()}).nullable().optional()});
export const repsSchema=z.object({data:z.object({items:z.array(repSchema),next_cursor:z.string().nullable(),directory:z.object({status:z.string(),snapshot_id:z.string().nullable(),taken_at:z.string().nullable(),accounts:z.array(z.object({rc_account_id:z.string(),snapshot_id:z.string().nullable(),taken_at:z.string().nullable(),status:z.string()})).optional(),users:z.array(directoryUserSchema),next_cursor:z.string().nullable()})})});
export const nudgeSchema=z.object({id:z.string(),revision:z.number(),outreach_record_id:z.string().nullable(),rc_account_id:z.string().nullable().optional(),rc_extension_id:z.string().nullable().optional(),rep_identity_link_id:z.string().nullable(),agent_id:z.string().nullable(),actor_id:z.string(),channel:z.enum(['team_messaging','sms_to_rep','pager']),purpose:z.enum(['call_suggestion','review_context']),template_key:z.string(),template_version:z.number(),body_as_sent:z.string(),status:z.enum(['pending','sent','failed','unknown_delivery','fallback_sent']),fallback_channel:z.literal('pager').nullable(),error_code:z.string().nullable(),created_at:z.string(),sent_at:z.string().nullable(),delivery_note:z.string(),automatic_resend:z.literal(false)});
export const nudgePreviewSchema=z.object({as_of:z.string(),data:z.object({body:z.string(),template_key:z.string(),template_version:z.number(),purpose:z.string(),expected_revision:z.number().nullable(),expected_rep_revision:z.number().nullable(),recipient:z.object({rc_account_id:z.string(),rc_extension_id:z.string(),directory_name:z.string().nullable().optional(),agent_id:z.string().nullable(),agent_name:z.string().nullable(),rep_identity_link_id:z.string().nullable(),channel:z.string()}),allowed_channels:z.array(z.string()),destination_evidence:z.string(),provider_destination_verified:z.boolean(),send_time_revalidation_required:z.boolean(),authorizes_send:z.literal(false)})});
export const nudgeSendSchema=z.object({data:z.object({operation_id:z.string(),replayed:z.boolean(),nudge:nudgeSchema})});
export const nudgeHistorySchema=z.object({as_of:z.string(),data:z.object({items:z.array(nudgeSchema),next_cursor:z.string().nullable()})});
export type DirectoryUser=z.infer<typeof directoryUserSchema>;
export type NudgePreview=z.infer<typeof nudgePreviewSchema>['data'];
export type NudgeRecord=z.infer<typeof nudgeSchema>;
/** Snapshot display only. Preview/send remain the send authority. Never invents a Team Messaging person id. */
export function destinationChannels(user: Pick<DirectoryUser,'extension_number'|'direct_numbers'>, personId?: string | null): string[] {
  const channels: string[] = [];
  if (personId) channels.push('team_messaging');
  if ((user.direct_numbers?.length ?? 0) === 1) channels.push('sms_to_rep');
  if (user.extension_number) channels.push('pager');
  return channels;
}
const assignment = z.object({ agent: agent.nullable(), origin: z.string().nullable() });
// call_state and provenance_state are server words, not Admin derivations, and stay z.string() so a
// server that grows a value still renders. Unmodelled keys are stripped, so every read field is here.
const derived = z.object({ overdue: z.boolean(), attention_band: z.number().nullable(), reasons: z.array(z.string()),
  review_badges: z.array(z.string()).optional(), call_blockers: z.array(z.string()), age_wall_ms: z.number(), age_staffed_ms: z.number(),
  call_state: z.string().optional(), provenance_state: z.string().optional() });
const subject = z.discriminatedUnion('kind', [z.object({ kind: z.literal('number_review'), contact_number_id: z.string() }),
  z.object({ kind: z.literal('lead'), model: z.enum(['FormLead','CallLead']), id: z.string() })]);
const followup = z.object({ id: z.string(), revision:z.number(), allowed_actions:z.array(availabilitySchema),kind: z.string(), description: z.string(), status: z.string(), due_at: z.string().nullable(),
  disposition:z.string().nullable().optional(),completion_basis:z.string().nullable().optional(),
  snoozed_until: z.string().nullable(), overdue: z.boolean(), origin: z.string(), assignment, promised_by: agent.nullable(), paused_channels: z.array(z.string()) });
// LP-01 §7: server-owned Lead progress. Every label is a server word; Admin never derives Quoted from
// Priority or policy from a code. Optional so a server without it still renders.
export const leadProgressSchema = z.object({ lead_ref: z.object({ model: z.enum(['FormLead','CallLead']), id: z.string() }),
  granot_priority: z.string().nullable(), priority_label: z.string(), quoted: z.boolean().nullable(),
  disposition: z.string(), disposition_label: z.string(), work_observed: z.boolean(), basis: z.string().nullable(), basis_label: z.string().nullable(),
  provenance: z.string(), source_origin: z.string().nullable(), source_applied_at: z.string().nullable(), last_progress_at: z.string().nullable(),
  first_work_observed_at: z.string().nullable(), closure: z.object({ basis: z.string(), closed_at: z.string().nullable() }).nullable(),
  override: z.object({ reason: z.string(), decided_at: z.string(), decided_by: z.string(), disposition_revision: z.string() }).nullable(),
  reopen_review_id: z.string().nullable(), disposition_revision: z.string(), explanation: z.string().nullable(), no_call_observed: z.boolean(), projected_at: z.string() });
export type LeadProgress = z.infer<typeof leadProgressSchema>;
// §14.1 ordering keys frozen into each Attention row; Admin renders server order and never sorts a page locally.
// Move assessment §8: score keys are optional so snapshots published before the contract still parse (missing reads as unknown).
export const sortKeysSchema = z.object({ next_action_due: z.string().nullable(), lead_received: z.string().nullable(), last_human_contact: z.string().nullable(), last_lead_progress: z.string().nullable(),
  transaction_intent: z.number().nullable().optional(), move_likelihood: z.number().nullable().optional(),
  assessment_status: z.string().nullable().optional(), assessment_stale: z.boolean().nullable().optional() });
export const ATTENTION_SORTS = ['attention','next_action_due','lead_received','last_human_contact','last_lead_progress','transaction_intent','move_likelihood'] as const;
export type AttentionSort = (typeof ATTENTION_SORTS)[number];
export const ATTENTION_SCORE_SORTS = ['transaction_intent','move_likelihood'] as const;
export type AttentionScoreSort = (typeof ATTENTION_SCORE_SORTS)[number];
export function isScoreSort(value: string | null | undefined): value is AttentionScoreSort { return (ATTENTION_SCORE_SORTS as readonly string[]).includes(value ?? ''); }
export const ATTENTION_SORT_DEFAULT_DIRECTION: Record<AttentionSort, 'asc'|'desc'> = { attention: 'asc', next_action_due: 'asc', lead_received: 'desc', last_human_contact: 'asc', last_lead_progress: 'desc', transaction_intent: 'desc', move_likelihood: 'desc' };
// Move assessment §8.1: the compact projection on an Outreach record. Server enums stay z.string() so a grown value still renders.
export const moveAssessmentSchema = z.object({ artifact_id: z.string().nullable(), status: z.string(), applicability: z.string(),
  transaction_intent: z.number().nullable(), move_likelihood: z.number().nullable(),
  transaction_intent_confidence: z.string().nullable(), move_likelihood_confidence: z.string().nullable(),
  context_as_of: z.string().nullable(), latest_conversation_at: z.string().nullable(), stale: z.boolean(), stale_reason: z.string().nullable(), published_at: z.string().nullable() });
export type MoveAssessment = z.infer<typeof moveAssessmentSchema>;
export type ScoreLabel = `${number} / 100` | 'Unknown' | 'Pending' | 'Not applicable' | 'Not assessed' | 'Unavailable';
/**
 * MA-01 §11: the card/sort wording for one score, straight from server facts. A number is `N / 100`
 * (never a percent); a real 0 stays `0 / 100`. `not_applicable` (status or read-time applicability)
 * wins over a number because the server sorts it as null. Assessed without a number is Unknown;
 * a queued job without a number is Pending; absent or `not_assessed` is Not assessed. Failed,
 * purged or unsupported results are Unavailable, never zero and never Unknown.
 */
export function scoreLabel(status: string | null | undefined, score: number | null | undefined, applicability?: string | null): ScoreLabel {
  if (status === 'not_applicable' || applicability === 'not_applicable') return 'Not applicable';
  if (typeof score === 'number' && Number.isFinite(score)) return `${Math.round(score)} / 100`;
  if (status === 'pending') return 'Pending';
  if (status === 'ready' || status === 'insufficient_evidence' || status === 'ambiguous_subject') return 'Unknown';
  if (status === 'failed' || status === 'purged' || status === 'unsupported' || status === 'unavailable') return 'Unavailable';
  return 'Not assessed';
}
export const NUMBER_SORTS = ['last_activity','last_human_conversation','first_observed'] as const;
export type NumberSort = (typeof NUMBER_SORTS)[number];
export function parseAttentionSort(value: string | null | undefined): AttentionSort { return (ATTENTION_SORTS as readonly string[]).includes(value ?? '') ? value as AttentionSort : 'attention'; }
export function parseNumberSort(value: string | null | undefined): NumberSort { return (NUMBER_SORTS as readonly string[]).includes(value ?? '') ? value as NumberSort : 'last_activity'; }
export function parseDirection(value: string | null | undefined, fallback: 'asc'|'desc'): 'asc'|'desc' { return value === 'asc' || value === 'desc' ? value : fallback; }
export const outreachSchema = z.object({ id: z.string(), revision: z.number(), subject, state: z.string(), reason: z.string().nullable(),
  allowed_actions:z.array(availabilitySchema),
  lead_progress: leadProgressSchema.nullable().optional(),
  lead_display:z.object({name:z.string().nullable(),job_no:z.string().nullable(),source_company:z.string().nullable()}).nullable().optional(),
  latest_number_call:z.object({id:z.string(),happened_at:z.string(),direction:z.string(),provider_result:z.string().nullable(),contact_type:z.string()}).nullable().optional(),
  related_record_links:z.array(z.object({model:z.enum(['FormLead','CallLead','BookedLead','CancelledLead']),id:z.string(),href:z.string(),certainty:z.string()})).optional(),
  lead_attachment:z.object({attachment_id:z.string(),lead_ref:z.object({model:z.enum(['FormLead','CallLead']),id:z.string()}),state:z.string(),certainty:z.string(),
   certainty_label:z.string().nullable(),decided_by:z.string(),decided_at:z.string().nullable(),confidence:z.number().nullable(),observed_at:z.string(),
   lead_display:z.object({name:z.string().nullable(),job_no:z.string().nullable()}).nullable()}).nullable().optional(),
  call_progress:z.object({state:z.string(),started_at:z.string(),started_by:z.string().nullable(),ended_at:z.string().nullable(),ended_by:z.string().nullable(),note:z.string().nullable()}).nullable().optional(),
  move_assessment: moveAssessmentSchema.nullable().optional(),
  primary_number: z.object({ id: z.string(), e164: z.string() }).nullable().optional(), assignment, followups: z.array(followup), derived,
  last_meaningful_contact_at: z.string().nullable() });
const coverage = z.object({ known_through: z.string().nullable(), gaps: z.array(z.object({ from:z.string(), to:z.string(), reason:z.string() })), ai_paused:z.boolean() });
// §7 Number card: the one resolved Lead's progress, or an explicit multiple/none. Never merged across Leads.
export const attachedLeadProgressSchema = z.object({ status: z.enum(['resolved','multiple','none']),
  lead_ref: z.object({ model: z.enum(['FormLead','CallLead']), id: z.string() }).optional(), lead_progress: leadProgressSchema.nullable().optional(),
  booking: z.object({ id: z.string(), cancelled: z.boolean() }).nullable().optional(), outreach_state: z.string().nullable().optional(),
  lead_display: z.object({ name: z.string().nullable(), job_no: z.string().nullable() }).nullable().optional() });
export type AttachedLeadProgress = z.infer<typeof attachedLeadProgressSchema>;
export const numberSearchSchema = z.object({ as_of:z.string(), coverage, data:z.object({
  items:z.array(z.object({ id:z.string(), revision:z.number(), e164:z.string(), provider_names:z.array(z.string()),
    classification:z.string(), eligibility:z.string(), linked:z.boolean(), last_activity_at:z.string(), first_observed_at:z.string().optional(),
    rollups:z.object({ interactions_total:z.number(), human_conversations_total:z.number(), attached_lead_count:z.number(), candidate_lead_count:z.number(), last_human_conversation_at:z.string().nullable().optional() }),
    attached_lead_progress: attachedLeadProgressSchema.optional() })),
  cursor:z.string().nullable(),
  // LP-06: the order the server applied to this page; absent on pre-sort servers.
  sort:z.object({ sort:z.string(), direction:z.enum(['asc','desc']) }).optional() }) });
export const timelineSchema = z.object({ as_of:z.string(), coverage, data:z.object({ number_id:z.string(),
  items:z.array(z.object({ id:z.string(), kind:z.string(), happened_at:z.string(), observed_at:z.string(), description:z.string(),
    evidence_refs:z.array(z.string()), detail:z.record(z.string(),z.json()) })), cursor:z.string().nullable() }) });
export const attentionSchema = z.object({ as_of: z.string(), coverage, data: z.object({ items: z.array(z.object({ subject_key:z.string(), subject,
  outreach: outreachSchema.nullable(), derived, sort_keys: sortKeysSchema.optional(),
  // Move assessment §8: `false` rows are reachable only in `view=all_outreach`; absent reads as in Attention.
  in_attention: z.boolean().optional() })), snapshot_id: z.string().nullable(), total_items:z.number().nullable(), cursor:z.string().nullable(), reason_counts:z.record(z.string(), z.number()).optional(),
  // Optional on the server DTO, so requiring it here would fail the whole Attention read on a page the server still publishes.
  status:z.enum(['ready','pending_projection']).optional(), stale:z.boolean().optional(),
  // §14.1: the sort the server produced this page under. Absent means the server has no sort contract; the UI shows "unavailable" rather than sorting locally.
  sort:z.string().optional(), direction:z.enum(['asc','desc']).optional(), view:z.string().optional(), freshness:z.string().optional() }) });
export const numberSchema = z.object({ as_of:z.string(), coverage, data:z.object({ id:z.string(), revision:z.number(), allowed_actions:z.array(availabilitySchema), e164:z.string(), classification:z.string(), eligibility:z.string(),
  outreach_records:z.array(outreachSchema), running_analysis:z.object({ text:z.string(), run_id:z.string().optional(), computed_at:z.string() }).nullable(),
  attachments:z.array(z.object({ id:z.string(), state:z.string(), certainty:z.string(), lead_ref:z.object({ model:z.string(), id:z.string() }) })),
  review_items:z.array(z.object({ id:z.string(), cause_kind:z.string(), state:z.string() })),
  restrictions:z.array(z.object({ id:z.string(), revision:z.number(), channels:z.array(z.string()), state:z.string(), until:z.string().nullable(), allowed_actions:z.array(availabilitySchema) })) }) });
export const outreachReadSchema = z.object({ as_of:z.string(), coverage, data:z.object({ outreach:outreachSchema }) });
const stage = z.object({ pending:z.number(), leased:z.number(), retry:z.number(), paused:z.number(), dead_letter:z.number(), oldest_queued_at:z.string().nullable() });
export const ownerCoverageSchema = z.object({ data:z.object({ as_of:z.string(), coverage:z.object({
  known_through:z.string().nullable(), gaps:z.array(z.object({ from:z.string(), to:z.string(), reason:z.string() })),
  capabilities:z.record(z.string(), z.enum(['ok','denied','unknown','unavailable'])), ai_paused:z.boolean(),
  recordings:z.object({ pending_discovery:z.number(), media_pending:z.number(), media_stored:z.number(), no_recording:z.number(), unavailable:z.number(), failed:z.number(), eligibility_undetermined:z.number() }).optional(),
  stages:z.object({ recording:stage, transcription:stage, analysis:stage, application:stage }),
  budget:z.object({ status:z.enum(['known','unknown']), month:z.string().nullable(), ceiling_cents:z.number(), actual_cents:z.number().nullable(), reserved_cents:z.number().nullable(), remaining_cents:z.number().nullable() }),
  // Optional: a server still on the previous revision publishes coverage without it, and the Owner read must not fail for that.
  analysis_admission:z.object({
    status:z.enum(['admitted','per_recording_ceiling','monthly_budget','no_active_period','configuration_missing']),
    estimated_cents_per_conversation:z.number().nullable(), per_recording_ceiling_cents:z.number(), model:z.string(), pricing_version:z.string().nullable(),
    limits:z.object({ steps:z.number(), context_tokens:z.number(), output_tokens:z.number(), total_input_tokens:z.number(), total_output_tokens:z.number(), elapsed_ms:z.number() }),
    paused:z.object({ per_recording_ceiling:z.number(), budget:z.number(), configuration:z.number() }),
    unresolved_reservations:z.object({ count:z.number(), estimated_cents:z.number() }),
  }).optional(),
  mapping_hygiene:z.object({ unmapped_inbound_numbers:z.number(), unmapped_directory_users:z.number().nullable(), last_directory_sync_at:z.string().nullable(), directory_status:z.enum(['stored','missing']) }),
  flags:z.record(z.string(), z.boolean()),
  models:z.object({ extraction:z.object({ name:z.string(), enabled:z.boolean() }), transcription:z.object({ name:z.string(), enabled:z.boolean() }) }),
  settings:z.object({ persisted:z.boolean(), revision:z.number(), version:z.string(), source:z.enum(['persisted','accepted_defaults']), timezone:z.string(), first_action_due_staffed_minutes:z.number(), missed_callback_due_staffed_minutes:z.number(), going_cold_staffed_minutes:z.number(), monthly_ceiling_cents:z.number(), per_recording_ceiling_cents:z.number().optional() }),
  backfill:z.object({
    available:z.boolean(),
    owner_triggered:z.literal(true),
    days:z.number().int().nonnegative(),
    planned:z.number().int().nonnegative().nullable(),
    partial:z.number().int().nonnegative().nullable(),
    complete:z.number().int().nonnegative().nullable(),
    failed:z.number().int().nonnegative().nullable(),
    known_complete_through:z.string().nullable(),
    gaps:z.array(z.object({ from:z.string(), to:z.string(), reason:z.string() })),
    note:z.string(),
  }),
}) }) });
export const settingsSchema = z.object({ as_of:z.string(), data:z.object({
  persisted:z.boolean(), revision:z.number(), source:z.enum(['persisted','accepted_defaults']),
  policy:z.object({ version:z.string(), timezone:z.string(), staffed_hours:z.array(z.object({ day:z.number().int().min(1).max(7), start_minute:z.number(), end_minute:z.number() })),
    first_action_due_staffed_minutes:z.number(), missed_callback_due_staffed_minutes:z.number(), going_cold_staffed_minutes:z.number(),
    monthly_ceiling_cents:z.number(), per_recording_ceiling_cents:z.number(), cooldown_attempts_24h:z.number(),
    enabled_capabilities:z.array(z.string()), retention:z.object({ audio_days:z.number(), redacted_days:z.number(), audit_days:z.number() }) }),
  flags:z.record(z.string(), z.boolean()),
  models:z.object({ extraction:z.object({ name:z.string(), enabled:z.boolean() }), transcription:z.object({ name:z.string(), enabled:z.boolean() }) }),
  updated_at:z.string().nullable(), updated_by:z.string().nullable(),
}) });
export type OwnerCoverage = z.infer<typeof ownerCoverageSchema>['data']['coverage'];
export type SettingsRead = z.infer<typeof settingsSchema>['data'];
export type Outreach = z.infer<typeof outreachSchema>;
export type Followup = z.infer<typeof followup>;
export type Agent = z.infer<typeof agent>;
export type AttentionRow = z.infer<typeof attentionSchema>['data']['items'][number];
export type NumberRead = z.infer<typeof numberSchema>;
export class SalesIntelligenceError extends Error {
  constructor(readonly code:string, readonly status:number, readonly requestId?:string) { super(code); }
}
export async function readSalesIntelligence<T>(path:string, schema:z.ZodType<T>, signal?:AbortSignal):Promise<T> {
  const separator = path.includes('?') ? '&' : '?';
  const response = await fetch(`/api/proxy/api/v1/admin/sales-intelligence/${path}${separator}scope=production`, { signal, cache:'no-store' });
  const body = await response.json();
  if (!response.ok || !body.ok) throw new SalesIntelligenceError(body.code ?? body.registry_code ?? 'READ_FAILED', response.status, body.request_id);
  return schema.parse(body);
}
export async function previewNudge(body: Record<string, unknown>, key: string) {
  const response = await fetch('/api/proxy/api/v1/admin/sales-intelligence/nudges/preview?scope=production', {
    method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify(body) });
  const payload = await response.json();
  if (!response.ok || !payload.ok) throw new SalesIntelligenceError(payload.code ?? payload.registry_code ?? 'COMMAND_FAILED', response.status, payload.request_id);
  return nudgePreviewSchema.parse(payload).data;
}
export async function sendNudge(body: Record<string, unknown>, key: string) {
  const response = await fetch('/api/proxy/api/v1/admin/sales-intelligence/nudges?scope=production', {
    method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, body: JSON.stringify(body) });
  const payload = await response.json();
  if (!response.ok || !payload.ok) throw new SalesIntelligenceError(payload.code ?? payload.registry_code ?? 'COMMAND_FAILED', response.status, payload.request_id);
  return nudgeSendSchema.parse(payload).data;
}
export async function listNudges(query: { outreach_record_id?: string; rc_account_id?: string; rc_extension_id?: string; cursor?: string; limit?: number }, signal?: AbortSignal) {
  const params = new URLSearchParams();
  if (query.outreach_record_id) params.set("outreach_record_id", query.outreach_record_id);
  params.set("limit", String(query.limit ?? 20));
  if (query.rc_account_id) params.set("rc_account_id", query.rc_account_id);
  if (query.rc_extension_id) params.set("rc_extension_id", query.rc_extension_id);
  if (query.cursor) params.set("cursor", query.cursor);
  return readSalesIntelligence(`nudges?${params}`, nudgeHistorySchema, signal);
}
export function nudgeDeliveryKind(status: NudgeRecord["status"]): "sent" | "failed" | "unknown" | "pending" {
  if (status === "sent" || status === "fallback_sent") return "sent";
  if (status === "failed") return "failed";
  if (status === "unknown_delivery") return "unknown";
  return "pending";
}
export type CommandIntent={path:string;method:'POST'|'PATCH';body:Record<string,unknown>;key:string};
const commandResultSchema=z.object({ok:z.literal(true),data:z.object({response:z.record(z.string(),z.json()),replayed:z.boolean()})});
export async function sendSalesIntelligence(intent:CommandIntent) {
 const response=await fetch(`/api/proxy/api/v1/admin/sales-intelligence/${intent.path}?scope=production`,{
  method:intent.method,headers:{'Content-Type':'application/json','Idempotency-Key':intent.key},body:JSON.stringify(intent.body)});
 const body=await response.json();
 if(!response.ok||!body.ok)throw new SalesIntelligenceError(body.code??body.registry_code??'COMMAND_FAILED',response.status,body.request_id);
 return commandResultSchema.parse(body).data;
}
