import { normalizationFixtureSchema } from "./normalizationFixture";

const leadStatement = {
  event_type: "lead_created",
  label: "Synthetic Forms",
  ref_no: "synthetic-tracking-ref-parity",
  customer_name: "Synthetic Customer",
  email: "customer@example.invalid",
  phone: "202-555-0110",
  priority: "1",
};

const leadExpectation = {
  observation_kind: "lead_snapshot",
  normalization_result: "valid",
  issue_codes: [],
  priority: { raw: "1", canonical: "1", valid: true },
  source_label: { raw: "Synthetic Forms", normalized: "synthetic forms" },
  identity: {
    form_ref_raw: "synthetic-tracking-ref-parity",
    normalized_form_ref: "synthetic-tracking-ref-parity",
  },
};

const bookingStatement = {
  event_type: "Booked",
  label: "Synthetic Forms",
  job_no: "synthetic-job-100",
  priority: "0",
};

const bookingExpectation = {
  observation_kind: "booking_action_snapshot",
  normalization_result: "valid",
  issue_codes: [],
  priority: { raw: "0", canonical: "0", valid: true },
  booking_action: { raw: "Booked", normalized: "booked" },
  source_label: { raw: "Synthetic Forms", normalized: "synthetic forms" },
  identity: { job_no_raw: "synthetic-job-100", normalized_job_no: "SYNTHETIC JOB 100" },
};

const fixtureInputs = [
  {
    schema_version: 1,
    fixture_id: "synthetic_ac03_tracking_reference_round_trip",
    acceptance_ids: ["AC-03"],
    channel: "granot_webhook",
    route_event_class: "lead_created",
    identity_setup: {
      persisted_form_ref_no: "synthetic-tracking-ref-01",
      posted_leadno: "synthetic-tracking-ref-01",
    },
    input: {
      kind: "payload",
      value: { event_type: "lead_created", ref_no: "synthetic-tracking-ref-01" },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      identity: {
        form_ref_raw: "synthetic-tracking-ref-01",
        normalized_form_ref: "synthetic-tracking-ref-01",
      },
    },
    forbidden_inferences: ["mongo_id_precedes_exact_form_reference"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac03_mongo_compatibility_after_exact_miss",
    acceptance_ids: ["AC-03"],
    channel: "granot_http_automation",
    operation_kind: "lead_snapshot_apply",
    operation_id: "synthetic-run-ac03:synthetic-action-mongo-fallback",
    input: {
      kind: "statement",
      value: { ref_no: "64b7f4d9e6c2a1b0f3d5e789" },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      identity: {
        form_ref_raw: "64b7f4d9e6c2a1b0f3d5e789",
        normalized_form_ref: "64b7f4d9e6c2a1b0f3d5e789",
      },
    },
    forbidden_inferences: ["mongo_id_precedes_exact_form_reference"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac03_blank_form_reference",
    acceptance_ids: ["AC-03"],
    channel: "granot_webhook",
    route_event_class: "lead_created",
    input: { kind: "payload", value: { event_type: "lead_created", ref_no: "   " } },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      identity: { form_ref_raw: "   " },
    },
    forbidden_inferences: ["blank_form_reference_is_exact_identity"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac03_not_provided_form_reference",
    acceptance_ids: ["AC-03"],
    channel: "browser_extension",
    operation_kind: "lead_snapshot_apply",
    operation_id: "11111111-1111-4111-8111-111111111103",
    input: { kind: "statement", value: { ref_no: "not_provided" } },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      identity: { form_ref_raw: "not_provided" },
    },
    forbidden_inferences: ["blank_form_reference_is_exact_identity"],
  },
  ...[
    ["zero_number", 0, "0", "granot_webhook", "priority_updated"],
    ["one_string", "1", "1", "browser_extension", "lead_snapshot_apply"],
    ["five_number", 5, "5", "granot_http_automation", "lead_snapshot_apply"],
    ["eight_string", "8", "8", "granot_webhook", "priority_updated"],
    ["leading_zero_five", "05", "5", "granot_webhook", "priority_updated"],
    [
      "twelve_digit_allowed",
      "123456789012",
      "123456789012",
      "browser_extension",
      "lead_snapshot_apply",
    ],
    ["all_zero_string", "000", "0", "granot_http_automation", "lead_snapshot_apply"],
  ].map(([suffix, raw, canonical, channel, authority], index) => ({
    schema_version: 1,
    fixture_id: `synthetic_ac05_priority_${suffix}`,
    acceptance_ids: ["AC-05"],
    channel,
    ...(channel === "granot_webhook"
      ? { route_event_class: authority }
      : channel === "browser_extension"
        ? {
            operation_kind: authority,
            operation_id: `22222222-2222-4222-8222-${String(index + 1).padStart(12, "0")}`,
          }
        : {
            operation_kind: authority,
            operation_id: `synthetic-run-ac05:synthetic-action-priority-${String(suffix).replaceAll("_", "-")}`,
          }),
    input: {
      kind: "statement",
      value: {
        ...(channel === "granot_webhook" ? { event_type: authority } : {}),
        priority: raw,
      },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      priority: { raw, canonical, valid: true },
    },
    forbidden_inferences: [
      ...(canonical === "1" || canonical === "5"
        ? []
        : ["priority_authorizes_broad_enrichment"]),
      "priority_sets_quoted_false",
    ],
  })),
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_missing_priority_update",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "priority_updated",
    input: { kind: "payload", value: { event_type: "priority_update" } },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "invalid",
      issue_codes: ["invalid_priority"],
      priority: { valid: false },
    },
    forbidden_inferences: ["priority_authorizes_broad_enrichment"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_malformed_priority_update",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "priority_updated",
    input: {
      kind: "payload",
      value: { event_type: "priority_updated", priority: "invalid-priority" },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "invalid",
      issue_codes: ["invalid_priority"],
      priority: { raw: "invalid-priority", valid: false },
    },
    forbidden_inferences: ["priority_authorizes_broad_enrichment"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_malformed_lead_created_priority",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "lead_created",
    input: {
      kind: "payload",
      value: { event_type: "lead_created", priority: "invalid-priority" },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid_with_issues",
      issue_codes: ["invalid_priority"],
      priority: { raw: "invalid-priority", valid: false },
    },
    forbidden_inferences: ["priority_authorizes_broad_enrichment"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_malformed_booked_priority",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "booking_status_changed",
    input: { kind: "payload", value: { event_type: "Booked", priority: "5.0" } },
    expected: {
      observation_kind: "booking_action_snapshot",
      normalization_result: "valid_with_issues",
      issue_codes: ["invalid_priority"],
      priority: { raw: "5.0", valid: false },
      booking_action: { raw: "Booked", normalized: "booked" },
    },
    forbidden_inferences: [
      "booking_action_is_lifecycle_transition",
      "booking_action_is_official_booking_fact",
    ],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_malformed_release_priority",
    acceptance_ids: ["AC-06"],
    channel: "granot_http_automation",
    operation_kind: "booking_action_apply",
    operation_id: "synthetic-run-ac06:synthetic-action-release-malformed-priority",
    input: { kind: "statement", value: { event_type: "Releas", priority: "-1" } },
    expected: {
      observation_kind: "booking_action_snapshot",
      normalization_result: "valid_with_issues",
      issue_codes: ["invalid_priority"],
      priority: { raw: "-1", valid: false },
      booking_action: { raw: "Releas", normalized: "release" },
    },
    forbidden_inferences: [
      "booking_action_is_lifecycle_transition",
      "booking_action_is_official_cancellation_fact",
    ],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_release_exact_alias",
    acceptance_ids: ["AC-06"],
    channel: "browser_extension",
    operation_kind: "booking_action_apply",
    operation_id: "33333333-3333-4333-8333-333333333306",
    input: { kind: "statement", value: { event_type: "Release" } },
    expected: {
      observation_kind: "booking_action_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      booking_action: { raw: "Release", normalized: "release" },
    },
    forbidden_inferences: [
      "booking_action_is_lifecycle_transition",
      "booking_action_is_official_cancellation_fact",
    ],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_booked_mixed_case_alias",
    acceptance_ids: ["AC-06"],
    channel: "granot_http_automation",
    operation_kind: "booking_action_apply",
    operation_id: "synthetic-run-ac06:synthetic-action-booked-mixed-case",
    input: { kind: "statement", value: { event_type: "bOoKeD" } },
    expected: {
      observation_kind: "booking_action_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      booking_action: { raw: "bOoKeD", normalized: "booked" },
    },
    forbidden_inferences: [
      "booking_action_is_lifecycle_transition",
      "booking_action_is_official_booking_fact",
    ],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_released_is_unsupported",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "booking_status_changed",
    input: { kind: "payload", value: { event_type: "Released" } },
    expected: {
      observation_kind: "booking_action_snapshot",
      normalization_result: "unsupported",
      issue_codes: ["unsupported_booking_action"],
      booking_action: { raw: "Released" },
    },
    forbidden_inferences: [
      "booking_action_is_lifecycle_transition",
      "booking_action_is_official_cancellation_fact",
    ],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac29_paid_overflow_deferred",
    acceptance_ids: ["AC-29"],
    channel: "granot_webhook",
    route_event_class: "lead_created",
    input: { kind: "payload", value: { event_type: "lead_created", label: "Paid Overflow" } },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      source_label: { raw: "Paid Overflow", normalized: "paid overflow" },
    },
    forbidden_inferences: ["deferred_source_authorizes_effects"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac29_auto_source_deferred",
    acceptance_ids: ["AC-29"],
    channel: "browser_extension",
    operation_kind: "lead_snapshot_apply",
    operation_id: "44444444-4444-4444-8444-444444444429",
    input: { kind: "statement", value: { label: "Auto" } },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      source_label: { raw: "Auto", normalized: "auto" },
    },
    forbidden_inferences: ["deferred_source_authorizes_effects"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac29_provider_type_auto_is_context_only",
    acceptance_ids: ["AC-29"],
    channel: "granot_http_automation",
    operation_kind: "lead_snapshot_apply",
    operation_id: "synthetic-run-ac29:synthetic-action-provider-type-auto",
    input: {
      kind: "statement",
      value: { label: "Synthetic Forms", type: "AUTO" },
    },
    expected: {
      observation_kind: "lead_snapshot",
      normalization_result: "valid",
      issue_codes: [],
      source_label: { raw: "Synthetic Forms", normalized: "synthetic forms" },
      provider_context: { type_raw: "AUTO" },
    },
    forbidden_inferences: ["type_drives_source_classification"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac05_lead_parity_webhook",
    acceptance_ids: ["AC-05"],
    channel: "granot_webhook",
    route_event_class: "lead_created",
    input: { kind: "statement", value: leadStatement },
    expected: leadExpectation,
    forbidden_inferences: [],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac05_lead_parity_extension",
    acceptance_ids: ["AC-05"],
    channel: "browser_extension",
    operation_kind: "lead_snapshot_apply",
    operation_id: "55555555-5555-4555-8555-555555555505",
    input: { kind: "statement", value: leadStatement },
    expected: leadExpectation,
    forbidden_inferences: [],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac05_lead_parity_automation",
    acceptance_ids: ["AC-05"],
    channel: "granot_http_automation",
    operation_kind: "lead_snapshot_apply",
    operation_id: "synthetic-run-ac05:synthetic-action-lead-parity",
    input: { kind: "statement", value: leadStatement },
    expected: leadExpectation,
    forbidden_inferences: [],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_booking_parity_webhook",
    acceptance_ids: ["AC-06"],
    channel: "granot_webhook",
    route_event_class: "booking_status_changed",
    input: { kind: "statement", value: bookingStatement },
    expected: bookingExpectation,
    forbidden_inferences: ["booking_action_is_official_booking_fact"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_booking_parity_extension",
    acceptance_ids: ["AC-06"],
    channel: "browser_extension",
    operation_kind: "booking_action_apply",
    operation_id: "66666666-6666-4666-8666-666666666606",
    input: { kind: "statement", value: bookingStatement },
    expected: bookingExpectation,
    forbidden_inferences: ["booking_action_is_official_booking_fact"],
  },
  {
    schema_version: 1,
    fixture_id: "synthetic_ac06_booking_parity_automation",
    acceptance_ids: ["AC-06"],
    channel: "granot_http_automation",
    operation_kind: "booking_action_apply",
    operation_id: "synthetic-run-ac06:synthetic-action-booking-parity",
    input: { kind: "statement", value: bookingStatement },
    expected: bookingExpectation,
    forbidden_inferences: ["booking_action_is_official_booking_fact"],
  },
];

export const normalizationFixtures = normalizationFixtureSchema.array().parse(fixtureInputs);
